Created Parkingspot Controller tests
PGBSNH19/spacepark-grupp-3-spacepark pull request #72
Opened 2020-09-22 12:18 UTC by fjalling

2020-09-22 12:22 UTC, pierre-nygard commented
Går inte igenom testerna. Säkerställ så branch klarar testerna och kan göra en build :)

2020-09-22 12:55 UTC, pierre-nygard approved these changes

2020-09-22 13:03 UTC, oskarmorell requested changes
GetParkingspotById, döp om metoden till expect NotNull

2020-09-22 13:09 UTC, samirehsani19 requested changes
feedbackrepo.Setup(x => x.Update<Feedback>(It.IsAny<Feedback>()));

behöver skicka en entity till Update() metoden i Repository

2020-10-06 07:39 UTC, oskarmorell approved these changes

2020-10-06 07:43 UTC, merged